keycloak:
  enabled: true
  realm: GuustoApp
  auth-server-url: http://localhost:8081/auth
  ssl-required: external
  resource: guusto-buy-gift
  verify-token-audience: true
  bearer-only: true
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  credentials:
     secret: 9bc5df20-4961-4bbc-bf9d-727b1d161dca
     
spring.main.allow-bean-definition-overriding: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url: jdbc:mysql://localhost:3306/guusto-new?useSSL=false
spring.datasource.username: root
spring.datasource.password: 123456

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true 

logging:
  level:
    org.apache.catalina: DEBUG
    org.keycloak: DEBUG
    root: DEBUG
    com.baeldung: TRACE

